//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeTicket.Shared.Localization.Forms.ExportSettingsLocal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExportSettingsFormLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExportSettingsFormLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TakeTicket.Shared.Localization.Forms.ExportSettingsLocal.ExportSettingsFormLocalizatio" +
                            "n", typeof(ExportSettingsFormLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ButtonExport {
            get {
                return ResourceManager.GetString("ButtonExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Settings.
        /// </summary>
        internal static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📄 File Format.
        /// </summary>
        internal static string GroupBoxFileFormat {
            get {
                return ResourceManager.GetString("GroupBoxFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📄 Export Scope.
        /// </summary>
        internal static string GroupBoxTypeExport {
            get {
                return ResourceManager.GetString("GroupBoxTypeExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        internal static string LabelExcel {
            get {
                return ResourceManager.GetString("LabelExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Type:.
        /// </summary>
        internal static string LabelExportType {
            get {
                return ResourceManager.GetString("LabelExportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of pages in every file.
        /// </summary>
        internal static string LabelPagesCount {
            get {
                return ResourceManager.GetString("LabelPagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        internal static string LabelPdf {
            get {
                return ResourceManager.GetString("LabelPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range (when selecting a specific range).
        /// </summary>
        internal static string LabelRange {
            get {
                return ResourceManager.GetString("LabelRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the range and export format.
        /// </summary>
        internal static string LabelSub {
            get {
                return ResourceManager.GetString("LabelSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Settings.
        /// </summary>
        internal static string LabelTitle {
            get {
                return ResourceManager.GetString("LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        internal static string LabelWord {
            get {
                return ResourceManager.GetString("LabelWord", resourceCulture);
            }
        }
    }
}
