//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeTicket.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesLocal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesLocal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TakeTicket.Shared.Localization.MessagesLocal", typeof(MessagesLocal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added successfully.
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not complete backup because.
        /// </summary>
        public static string BackupFailed {
            get {
                return ResourceManager.GetString("BackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup completed successfully.
        /// </summary>
        public static string BackupSuccess {
            get {
                return ResourceManager.GetString("BackupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus is full.
        /// </summary>
        public static string BusFull {
            get {
                return ResourceManager.GetString("BusFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus not found.
        /// </summary>
        public static string BusNotFound {
            get {
                return ResourceManager.GetString("BusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose recovery method.
        /// </summary>
        public static string ChooseRecoveryMethod {
            get {
                return ResourceManager.GetString("ChooseRecoveryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation sent successfully.
        /// </summary>
        public static string ConfirmMessageSuccess {
            get {
                return ResourceManager.GetString("ConfirmMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string is corrupted or unencrypted. Settings will open..
        /// </summary>
        public static string ConnectionStringInvalid {
            get {
                return ResourceManager.GetString("ConnectionStringInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection text saved successfully, please restart the application.
        /// </summary>
        public static string ConnectionTextSaved {
            get {
                return ResourceManager.GetString("ConnectionTextSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database setup is required first.
        /// </summary>
        public static string DatabaseSetupRequired {
            get {
                return ResourceManager.GetString("DatabaseSetupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection failed. Settings will open..
        /// </summary>
        public static string DbConnectionFailed {
            get {
                return ResourceManager.GetString("DbConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteDialogCaption {
            get {
                return ResourceManager.GetString("DeleteDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this? This action cannot be undone..
        /// </summary>
        public static string DeleteDialogText {
            get {
                return ResourceManager.GetString("DeleteDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully.
        /// </summary>
        public static string EditSuccess {
            get {
                return ResourceManager.GetString("EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        public static string EmptyMessageCaption {
            get {
                return ResourceManager.GetString("EmptyMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data grid is empty. This action cannot be performed..
        /// </summary>
        public static string EmptyMessageText {
            get {
                return ResourceManager.GetString("EmptyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter answer.
        /// </summary>
        public static string EnterAnswer {
            get {
                return ResourceManager.GetString("EnterAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter recovery code.
        /// </summary>
        public static string EnterRecoveryCode {
            get {
                return ResourceManager.GetString("EnterRecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username.
        /// </summary>
        public static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again..
        /// </summary>
        public static string ErrorGeneralMessage {
            get {
                return ResourceManager.GetString("ErrorGeneralMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error.
        /// </summary>
        public static string FieldReqCaption {
            get {
                return ResourceManager.GetString("FieldReqCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields marked with * are required. Please fill them in..
        /// </summary>
        public static string FieldsReqText {
            get {
                return ResourceManager.GetString("FieldsReqText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading image.
        /// </summary>
        public static string ImageLoadError {
            get {
                return ResourceManager.GetString("ImageLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid passenger.
        /// </summary>
        public static string InvalidPassenger {
            get {
                return ResourceManager.GetString("InvalidPassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ No data to export.
        /// </summary>
        public static string NoDataToExport {
            get {
                return ResourceManager.GetString("NoDataToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No security question for this user.
        /// </summary>
        public static string NoSecurityQuestionForUser {
            get {
                return ResourceManager.GetString("NoSecurityQuestionForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger name is required.
        /// </summary>
        public static string PassengerNameRequired {
            get {
                return ResourceManager.GetString("PassengerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger not found.
        /// </summary>
        public static string PassengerNotFound {
            get {
                return ResourceManager.GetString("PassengerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required.
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery code expired.
        /// </summary>
        public static string RecoveryCodeExpired {
            get {
                return ResourceManager.GetString("RecoveryCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid recovery code.
        /// </summary>
        public static string RecoveryCodeInvalid {
            get {
                return ResourceManager.GetString("RecoveryCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Code.
        /// </summary>
        public static string RecoveryCodeMethod {
            get {
                return ResourceManager.GetString("RecoveryCodeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery code was not requested.
        /// </summary>
        public static string RecoveryCodeNotRequested {
            get {
                return ResourceManager.GetString("RecoveryCodeNotRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Question.
        /// </summary>
        public static string RecoveryQuestionMethod {
            get {
                return ResourceManager.GetString("RecoveryQuestionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration message sent successfully.
        /// </summary>
        public static string RegistrationMessageSuccess {
            get {
                return ResourceManager.GetString("RegistrationMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter security question and answer.
        /// </summary>
        public static string SecurityQuestionAnswerRequired {
            get {
                return ResourceManager.GetString("SecurityQuestionAnswerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select passenger.
        /// </summary>
        public static string SelectPassenger {
            get {
                return ResourceManager.GetString("SelectPassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Connection Error.
        /// </summary>
        public static string ServerErrorCaption {
            get {
                return ResourceManager.GetString("ServerErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A server connection error occurred. Please try again later or check your system settings..
        /// </summary>
        public static string ServerErrorText {
            get {
                return ResourceManager.GetString("ServerErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ShowReDeleteFiledCaption {
            get {
                return ResourceManager.GetString("ShowReDeleteFiledCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the entire row before deleting..
        /// </summary>
        public static string ShowReDeleteFiledText {
            get {
                return ResourceManager.GetString("ShowReDeleteFiledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket created:.
        /// </summary>
        public static string TicketCreated {
            get {
                return ResourceManager.GetString("TicketCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create ticket.
        /// </summary>
        public static string TicketCreationFailed {
            get {
                return ResourceManager.GetString("TicketCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket not found.
        /// </summary>
        public static string TicketNotFound {
            get {
                return ResourceManager.GetString("TicketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the ticket.
        /// </summary>
        public static string TicketOpenFailed {
            get {
                return ResourceManager.GetString("TicketOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User verified, choose recovery method.
        /// </summary>
        public static string UserVerifiedChooseRecoveryMethod {
            get {
                return ResourceManager.GetString("UserVerifiedChooseRecoveryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify username first.
        /// </summary>
        public static string VerifyUsernameFirst {
            get {
                return ResourceManager.GetString("VerifyUsernameFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait one minute before requesting a new code.
        /// </summary>
        public static string WaitBeforeNewCode {
            get {
                return ResourceManager.GetString("WaitBeforeNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting list is full.
        /// </summary>
        public static string WaitingListFull {
            get {
                return ResourceManager.GetString("WaitingListFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong answer.
        /// </summary>
        public static string WrongAnswer {
            get {
                return ResourceManager.GetString("WrongAnswer", resourceCulture);
            }
        }
    }
}
