<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
	  <AssemblyName>TakeTicket</AssemblyName>
	  <RootNamespace>TakeTicket</RootNamespace>
	  
	  <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	  <Nullable>enable</Nullable>
	  <ImplicitUsings>enable</ImplicitUsings>
    <Authors>Hasan</Authors>
    <Company>Hasanqp</Company>
    <Description>Professional Travel Agency Management System</Description>
    <Copyright>© 2026 TakeTicket Software. All rights reserved.</Copyright>
    <ApplicationIcon>TakeTicket.ico</ApplicationIcon>
    <PackageIcon>TakeTicket.png</PackageIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>5</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="TakeTicket.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="FastMember" Version="1.5.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.17">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="QuestPDF" Version="2026.2.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TakeTicket.Application\TakeTicket.Application.csproj" />
    <ProjectReference Include="..\TakeTicket.Domain\TakeTicket.Domain.csproj" />
    <ProjectReference Include="..\TakeTicket.Infrastructure\TakeTicket.Infrastructure.csproj" />
    <ProjectReference Include="..\TakeTicket.Shared\TakeTicket.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Gui\PassengerEnrollmentGui\AddPassengerForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Gui\PassengerEnrollmentGui\PassengerUserControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\SystemRecordsGui\SystemRecordsUserControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\UsersGui\ForgotPasswordForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Gui\UsersGui\RestPasswordForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Gui\UsersGui\UsersUserControl.cs" />
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator></Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Resources\TakeTicket.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>