//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeTicket.Shared.Localization.Forms.PassengerEnrollmentLocal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddPassengerFormLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddPassengerFormLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TakeTicket.Shared.Localization.Forms.PassengerEnrollmentLocal.AddPassengerFormLocaliza" +
                            "tion", typeof(AddPassengerFormLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and close.
        /// </summary>
        internal static string ButtonSaveAndClose {
            get {
                return ResourceManager.GetString("ButtonSaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / Edit Passenger 👤.
        /// </summary>
        internal static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎫 Booking type.
        /// </summary>
        internal static string GroupBoxBookingType {
            get {
                return ResourceManager.GetString("GroupBoxBookingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚌 Choose a bus.
        /// </summary>
        internal static string GroupBoxChooseBus {
            get {
                return ResourceManager.GetString("GroupBoxChooseBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👤 Passenger information.
        /// </summary>
        internal static string GroupBoxPassengerInfo {
            get {
                return ResourceManager.GetString("GroupBoxPassengerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎟 Seats summary.
        /// </summary>
        internal static string GroupBoxSeatsSummary {
            get {
                return ResourceManager.GetString("GroupBoxSeatsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚌 Trip information display.
        /// </summary>
        internal static string GroupBoxTripInfo {
            get {
                return ResourceManager.GetString("GroupBoxTripInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string LabelAddress {
            get {
                return ResourceManager.GetString("LabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus No.
        /// </summary>
        internal static string LabelBusNumberText {
            get {
                return ResourceManager.GetString("LabelBusNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        internal static string LabelDeparture {
            get {
                return ResourceManager.GetString("LabelDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string LabelDetails {
            get {
                return ResourceManager.GetString("LabelDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string LabelNationality {
            get {
                return ResourceManager.GetString("LabelNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LabelPassengerName {
            get {
                return ResourceManager.GetString("LabelPassengerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport.
        /// </summary>
        internal static string LabelPassportNumber {
            get {
                return ResourceManager.GetString("LabelPassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string LabelPhoneNumber {
            get {
                return ResourceManager.GetString("LabelPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string LabelReturn {
            get {
                return ResourceManager.GetString("LabelReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter passenger details and select the bus and journey.
        /// </summary>
        internal static string LabelSub {
            get {
                return ResourceManager.GetString("LabelSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / Edit passenger.
        /// </summary>
        internal static string LabelTitle {
            get {
                return ResourceManager.GetString("LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip type.
        /// </summary>
        internal static string LabelTripType {
            get {
                return ResourceManager.GetString("LabelTripType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Seat.
        /// </summary>
        internal static string RadioExtraSeat {
            get {
                return ResourceManager.GetString("RadioExtraSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Seat.
        /// </summary>
        internal static string RadioMainSeat {
            get {
                return ResourceManager.GetString("RadioMainSeat", resourceCulture);
            }
        }
    }
}
