//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeTicket.Shared.Localization.Forms.SettingsLocal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsFormLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsFormLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TakeTicket.Shared.Localization.Forms.SettingsLocal.SettingsFormLocalization", typeof(SettingsFormLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string ButtonBackup {
            get {
                return ResourceManager.GetString("ButtonBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Backup.
        /// </summary>
        internal static string ButtonRestoreBackup {
            get {
                return ResourceManager.GetString("ButtonRestoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Connection.
        /// </summary>
        internal static string ButtonSaveConString {
            get {
                return ResourceManager.GetString("ButtonSaveConString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save general settings.
        /// </summary>
        internal static string ButtonSaveGeneral {
            get {
                return ResourceManager.GetString("ButtonSaveGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Language.
        /// </summary>
        internal static string ButtonSaveLanguage {
            get {
                return ResourceManager.GetString("ButtonSaveLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛢️ Backup and Restore.
        /// </summary>
        internal static string GroupBoxBackup {
            get {
                return ResourceManager.GetString("GroupBoxBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛢️ DataBases.
        /// </summary>
        internal static string GroupBoxDatabases {
            get {
                return ResourceManager.GetString("GroupBoxDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙️ General Settings.
        /// </summary>
        internal static string GroupBoxGeneral {
            get {
                return ResourceManager.GetString("GroupBoxGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔠 Languages.
        /// </summary>
        internal static string GroupBoxLanguages {
            get {
                return ResourceManager.GetString("GroupBoxLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to upload logo.
        /// </summary>
        internal static string LabelClickToUpload {
            get {
                return ResourceManager.GetString("LabelClickToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Type:.
        /// </summary>
        internal static string LabelConnectionType {
            get {
                return ResourceManager.GetString("LabelConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataBase.
        /// </summary>
        internal static string LabelDataBase {
            get {
                return ResourceManager.GetString("LabelDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Timeout (sec).
        /// </summary>
        internal static string LabelNotificationTimeout {
            get {
                return ResourceManager.GetString("LabelNotificationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Records Displayed.
        /// </summary>
        internal static string LabelNumberOfRecords {
            get {
                return ResourceManager.GetString("LabelNumberOfRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Logo.
        /// </summary>
        internal static string LabelOrganizationLogo {
            get {
                return ResourceManager.GetString("LabelOrganizationLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        internal static string LabelOrganizationName {
            get {
                return ResourceManager.GetString("LabelOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string LabelServer {
            get {
                return ResourceManager.GetString("LabelServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings | DataBase | Language | Backup.
        /// </summary>
        internal static string LabelSub {
            get {
                return ResourceManager.GetString("LabelSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time connection (Seconds).
        /// </summary>
        internal static string LabelTimeConnection {
            get {
                return ResourceManager.GetString("LabelTimeConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string LabelTitle {
            get {
                return ResourceManager.GetString("LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string LabelUserName {
            get {
                return ResourceManager.GetString("LabelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string LinkLabelUpload {
            get {
                return ResourceManager.GetString("LinkLabelUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string RadioLocalCon {
            get {
                return ResourceManager.GetString("RadioLocalCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string RadioNetworkCon {
            get {
                return ResourceManager.GetString("RadioNetworkCon", resourceCulture);
            }
        }
    }
}
